### PR TITLE
Improve test coverage, remove `asm` feature, alignment fixes/precautions

### LINKED ISSUE #44: Remove `asm` feature
`asm` is getting stabilized upstream and the feature is not strictly necessary anymore for the implementation.
Note that only the host side needs it, currently exclusively for the purpose of executing syscalls.

Unfortunately `miri` does not support inline assembly at the time of writing (https://github.com/rust-lang/miri/issues/1045, https://github.com/rust-lang/miri/issues/11 is the tracking issue)

Few options here:
1. Remove `miri` and `asm` feature - we lose potential for testing against UB on CI
2. Disable `miri` for tests involving host side - greatly diminishes the benefit of actually using `miri`
3. Disable `miri` selectively for each test involving host side and inline assembly - this is going to be quite tedious to maintain
4. It's not broken, so don't fix it - we can simply wait until inline assembly is supported by `miri`. That may take long and that means we have to maintain the feature within the implementation, but that is actually fairly trivial, since the host simply ignores the syscalls when feature is disabled. Note, that it is possible that will have some mechanism in place for selectively disabling/enabling host-side call handlers at runtime in the future, if we had such functionality, we could then simply disable all calls requiring `asm` when `miri` is enabled and drop the feature.

For now, I vote for 4. and suggest to revisit this in a few sprints.

Refs https://github.com/rust-lang/rust/pull/91728 https://github.com/enarx/enarx/issues/1178

### PR DESCRIPTION
**Pull request by rvolosatovs**
Closes enarx/sallyport#44 
Refs enarx/enarx#1730

### CODE REVIEW

File: src/v2/tests/integration_tests.rs [hunk 1]
```diff
@@ -213,46 +358,60 @@ fn recvfrom() {
         });
 
         let mut buf = [0u8; EXPECTED.len()];
-        let mut src_addr: sockaddr = unsafe { mem::zeroed() };
+        let mut src_addr: libc::sockaddr = unsafe { mem::zeroed() };
         let mut src_addr_bytes = unsafe {
-            slice::from_raw_parts_mut(&mut src_addr as *mut _ as _, size_of::<sockaddr>())
+            slice::from_raw_parts_mut(&mut src_addr as *mut _ as _, size_of::<libc::sockaddr>())
```
Comment (rvolosatovs) [inline src/v2/tests/integration_tests.rs:363]: Sorry for this diff, I will either fix this in an upcoming PR if we can merge this one quick or I can remove it from here

**Review by haraldh — APPROVED** [review]
